import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { NextConfig } from 'next';

const here = dirname(fileURLToPath(import.meta.url));
const cacheHandlerPath = resolve(here, '.generated/cache-handler.cjs');

export const securityHeaders = [
  { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
  },
  { key: 'Cross-Origin-Opener-Policy', value: 'same-origin-allow-popups' },
];

/** A production build without the shared handler would silently fall back to a per-instance cache: refuse. */
function handlerConfig(): Partial<NextConfig> {
  if (existsSync(cacheHandlerPath))
    return { cacheHandler: cacheHandlerPath, cacheMaxMemorySize: 0 };
  if (process.env.NODE_ENV === 'production') {
    throw new Error(
      'Shared cache handler bundle missing: run `node scripts/build.mjs` (pnpm build does this in prebuild).',
    );
  }
  return {};
}

const config: NextConfig = {
  // This repo curates its own AGENTS.md; do not let Next generate agent files.
  agentRules: false,
  output: 'standalone',
  outputFileTracingRoot: resolve(here, '../..'),
  poweredByHeader: false,
  reactStrictMode: true,
  transpilePackages: [
    '@sold/core',
    '@sold/db',
    '@sold/commerce',
    '@sold/payments',
    '@sold/content',
    '@sold/storefront',
    '@sold/identity',
  ],
  serverExternalPackages: ['pg', 'ioredis', 'pino', 'prom-client'],
  // A stable build ID is required so every replica of a release agrees (Section 8A.3).
  generateBuildId: async () => process.env.SOLD_BUILD_ID ?? 'dev',
  // Shared, Redis-backed ISR/data cache (Section 8A.2): generated by `scripts/build.mjs`.
  ...handlerConfig(),
  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }];
  },
};

export default config;
