// Generates `.generated/theme.ts`: a static import of the theme selected by `theme.preset` in sold.config.ts.
// `default` is the theme Base ships; anything else is a customer-owned folder `themes/<preset>/` (see docs/theming.md).
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(webRoot, '../..');
const out = resolve(webRoot, '.generated/theme.ts');

const { default: config } = (await import(resolve(repoRoot, 'sold.config.ts'))) as {
  default: { theme: { preset: string } };
};
const preset = config.theme.preset;

let target: string;
if (preset === 'default') {
  target = '@sold/storefront/default-theme';
} else {
  if (!/^[a-z][a-z0-9-]*$/.test(preset))
    throw new Error(`theme.preset "${preset}" is not a valid theme folder name`);
  const dir = resolve(repoRoot, 'themes', preset);
  const entry = ['index.ts', 'index.tsx', 'theme.ts', 'theme.tsx']
    .map((f) => resolve(dir, f))
    .find((p) => existsSync(p));
  if (!entry)
    throw new Error(
      `theme.preset is "${preset}" but themes/${preset}/index.ts does not exist. Run: pnpm sold theme:new ${preset}`,
    );
  target = relative(dirname(out), entry.replace(/\.tsx?$/, '')).replaceAll('\\', '/');
  if (!target.startsWith('.')) target = `./${target}`;
}

await mkdir(dirname(out), { recursive: true });
await writeFile(
  out,
  `// Generated by scripts/sync-theme.ts. Do not edit.\nexport { default } from '${target}';\n`,
);
console.log(`theme: ${preset}`);
