variable "env_id" {
  description = "Generated by `sold env:up`: <customer>-eph-<slug>-<hash>."
  type        = string
}

variable "environment" {
  type = string
}

variable "release_version" {
  description = "<base-version>+<customer>.<instance-build> of the build under preview."
  type        = string
}

variable "image" {
  description = "Digest-pinned web image built by CI for this commit."
  type        = string
}

variable "worker_image" {
  description = "Digest-pinned worker image (Dockerfile target worker); null = same as image."
  type        = string
  default     = null
}

variable "migrate_image" {
  description = "Digest-pinned image with a migrate entrypoint; null = same as image."
  type        = string
  default     = null
}

variable "expires_at" {
  description = "RFC 3339 expiry stamped by `sold env:up` (default now + 48h)."
  type        = string
}

variable "subscription_id" {
  description = "Customer Azure subscription for non-production."
  type        = string
}

variable "region" {
  type = string
}

variable "owner" {
  type = string
}

variable "alert_emails" {
  type = list(string)
}

variable "registry" {
  type = object({
    id           = string
    login_server = string
    grant_pull   = optional(bool, true)
  })
}

variable "cloudflare" {
  type = object({
    enabled    = bool
    account_id = optional(string)
    zone_id    = optional(string)
    hostname   = optional(string)
  })
}

variable "access" {
  type = object({
    enabled               = bool
    allowed_email_domains = optional(list(string), [])
    allowed_emails        = optional(list(string), [])
  })
}

variable "email" {
  type = object({
    enabled                  = bool
    sending_domain           = optional(string)
    spf_includes             = optional(list(string), [])
    dkim_records             = optional(map(object({ name = string, type = string, content = string })), {})
    dmarc_policy             = optional(string, "none")
    dmarc_report_address     = optional(string)
    cloudflare_email_sending = optional(bool, false)
  })
  default = { enabled = false }
}

variable "paused" {
  type    = bool
  default = false
}

# Supplied by -var-file=../../../profiles/ephemeral.tfvars
variable "profile_settings" {
  type = object({
    resource_lock          = bool
    protect_stateful       = bool
    redis_enabled          = bool
    service_bus_enabled    = bool
    private_endpoints      = bool
    revision_mode          = string
    postgres_password_auth = bool
    generate_app_secrets   = bool
    log_retention_days     = number
    log_daily_quota_gb     = number
    budget_monthly         = number
    origin_cert_days       = number
  })
}

variable "tier_settings" {
  type = object({
    web_cpu                  = number
    web_memory               = string
    web_min_replicas         = number
    web_max_replicas         = number
    web_concurrency          = number
    worker_cpu               = number
    worker_memory            = string
    worker_min_replicas      = number
    worker_max_replicas      = number
    dedicated_profile        = optional(object({ name = string, type = string, minimum_count = number, maximum_count = number }))
    db_sku_name              = string
    db_storage_mb            = number
    db_ha_mode               = string
    db_read_replica_count    = number
    db_backup_retention_days = number
    db_geo_redundant_backup  = bool
    redis_sku_name           = string
    redis_ha                 = bool
    servicebus_sku           = string
    servicebus_capacity      = number
    zone_redundant           = bool
  })
}
