import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';
import { CliError } from '../lib/errors';

/**
 * `.sold/base-manifest.json` (Base-owned): which paths Base owns, which the customer owns, and which
 * are generated by tooling. Customers never edit Base-owned paths; upgrades replace them wholesale.
 */
export const baseManifestSchema = z
  .object({
    schemaVersion: z.literal(1),
    description: z.string().optional(),
    /** Replaced from upstream by `upgrade:plan`. Editing these outside an `upgrade/*` branch is drift. */
    baseOwned: z.array(z.string().min(1)).min(1),
    /** Never touched by upgrades. */
    customerOwned: z.array(z.string().min(1)),
    /** Rewritten by tooling (lockfile, base-version). Ignored by the drift check. */
    generated: z.array(z.string().min(1)).default([]),
  })
  .strict();

export type BaseManifest = z.infer<typeof baseManifestSchema>;
export type Ownership = 'base' | 'customer' | 'generated' | 'unowned';

export const MANIFEST_PATH = '.sold/base-manifest.json';

export function parseManifest(text: string, origin: string): BaseManifest {
  let json: unknown;
  try {
    json = JSON.parse(text);
  } catch (error) {
    throw new CliError(`${origin} is not valid JSON: ${(error as Error).message}`);
  }
  const parsed = baseManifestSchema.safeParse(json);
  if (!parsed.success) {
    throw new CliError(
      `${origin} is invalid:\n${parsed.error.issues.map((i) => `  ${i.path.join('.') || '(root)'}: ${i.message}`).join('\n')}`,
    );
  }
  return parsed.data;
}

export async function readManifest(cwd: string): Promise<BaseManifest> {
  let text: string;
  try {
    text = await readFile(join(cwd, MANIFEST_PATH), 'utf8');
  } catch {
    throw new CliError(`${MANIFEST_PATH} not found: is this a Sold repository?`);
  }
  return parseManifest(text, MANIFEST_PATH);
}

const regexCache = new Map<string, RegExp>();

/**
 * Path patterns: `dir/` or `dir/**` match a subtree, `**` crosses directories, `*` and `?` stay within a
 * path segment, everything else is literal. Patterns are repository-relative with forward slashes.
 */
export function globToRegExp(pattern: string): RegExp {
  const cached = regexCache.get(pattern);
  if (cached) return cached;
  let p = pattern.replace(/^\.\//, '');
  if (p.endsWith('/')) p += '**';
  let out = '^';
  for (let i = 0; i < p.length; i += 1) {
    const ch = p[i] ?? '';
    if (ch === '*') {
      if (p[i + 1] === '*') {
        i += 1;
        if (p[i + 1] === '/') {
          i += 1;
          out += '(?:.*/)?';
        } else {
          out += '.*';
        }
      } else {
        out += '[^/]*';
      }
    } else if (ch === '?') {
      out += '[^/]';
    } else {
      out += ch.replace(/[.+^${}()|[\]\\]/g, '\\$&');
    }
  }
  const regex = new RegExp(`${out}$`);
  regexCache.set(pattern, regex);
  return regex;
}

export function matchesAny(path: string, patterns: readonly string[]): boolean {
  return patterns.some((pattern) => globToRegExp(pattern).test(path));
}

/** Generated wins over base wins over customer: the most specific statement about a path. */
export function classify(path: string, manifest: BaseManifest): Ownership {
  if (matchesAny(path, manifest.generated)) return 'generated';
  if (matchesAny(path, manifest.baseOwned)) return 'base';
  if (matchesAny(path, manifest.customerOwned)) return 'customer';
  return 'unowned';
}
